lang: ko
locale: ko_KR
timezone: Asia/Seoul
title: Exception
description: Hello, World!
permalink: /:year-:month-:day-:title/
date_format: "%Y.%m.%d"
profile: "https://avatars.githubusercontent.com/u/43216569?v=4&s=300"
author: Kiro Shin
email: "mulgom -@- gmail.com"
tagline: App Developer.
github: https://github.com/kiroshin/
instagram: https://www.instagram.com/kiro.shin_/
foot-log: Take pride in your work.

sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

exclude:
  - Gemfile
  - README

plugins:
  - jekyll-sitemap
